package main

const (
	EXPORT_TYPE_SHA256 = 1
	EXPORT_TYPE_MD5    = 2
	EXPORT_TYPE_DOMAIN = 3
	EXPORT_TYPE_HOST   = 4
)

const (
	SEARCH_TYPE_FILE_PATH     = 1
	SEARCH_TYPE_LAUNCH_STRING = 2
	SEARCH_TYPE_LOCATION      = 3
	SEARCH_TYPE_ITEM_NAME     = 4
	SEARCH_TYPE_PROFILE       = 5
	SEARCH_TYPE_DESCRIPTION   = 6
	SEARCH_TYPE_COMPANY       = 7
	SEARCH_TYPE_SIGNER        = 8
	SEARCH_TYPE_SHA256        = 9
	SEARCH_TYPE_MD5           = 10
)

const (
	DATA_TYPE_ALERTS   = 1
	DATA_TYPE_AUTORUNS = 2
)

const (
	VERIFIED_ALL   = 0
	VERIFIED_TRUE  = 1
	VERIFIED_FALSE = 2
	VERIFIED_MS    = 3
)
